### ISSUE TITLE
can not run llama 3.1 405B

### ISSUE THREAD

**Issue by taozhiyuai** [lyogavin/airllm#158]
run on Mac M3 Max 128GB

run this code
```
from transformers import AutoModel, AutoTokenizer  

model = AutoModel.from_pretrained("unsloth/Meta-Llama-3.1-405B-Instruct-bnb-4bit")  
tokenizer = AutoTokenizer.from_pretrained("unsloth/Meta-Llama-3.1-405B-Instruct-bnb-4bit")  

input_text = ['What is the capital of China? Introduce the history of this city.']  
input_tokens = tokenizer(input_text, return_tensors="pt", padding=True, truncation=True, max_length=128)  

generation_output = model.generate(input_tokens['input_ids'].cuda(), max_new_tokens=10, return_dict_in_generate=True)  

output = tokenizer.decode(generation_output.sequences[0], skip_special_tokens=True)  

print(output)
```

Error is 

`Unused kwargs: ['_load_in_4bit', '_load_in_8bit', 'quant_method']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
Traceback (most recent call last):
  File "/Users/taozhiyu/Downloads/airllm.py", line 3, in <module>
    model = AutoModel.from_pretrained("unsloth/Meta-Llama-3.1-405B-Instruct-bnb-4bit")  
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/transformers/modeling_utils.py", line 3354, in from_pretrained
    hf_quantizer.validate_environment(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/transformers/quantizers/quantizer_bnb_4bit.py", line 62, in validate_environment
    raise RuntimeError("No GPU found. A GPU is needed for quantization.")
RuntimeError: No GPU found. A GPU is needed for quantization.`

**Comment by Tdrinker** [comment]
the error message is self explanatory.

You do not have GPU.

**Comment by taozhiyuai** [comment]
> the error message is self explanatory.
> 
> You do not have GPU.

apple Mac Pro m3 max

**Comment by lyogavin** [comment]
This area was substantially reworked in v3.0.x: AirLLM now wraps the standard Transformers model and lets it own the forward/generate pass, and shard handling, runtime dtype, and the attention-implementation fallback were all fixed. This should be resolved on v3.0.1. Closing — please `pip install -U airllm` (>=3.0.1) and reopen with details if you still hit it.
