### ISSUE TITLE
Circular import error in importing partially initialised module airllm

### ISSUE THREAD

**Issue by samarthpusalkar** [lyogavin/airllm#161]
I have MacBook M1 silicon

I created a native python env with:

```
CONDA_SUBDIR=osx-arm64 conda create -n native numpy -c conda-forge
```

then installed mlx and airllm

```
python -m pip install mlx
python -m pip install airllm
```

then running the following in python file gave the following error:

```
from airllm import AutoModel
```

Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/samarthpusalkar/Desktop/airllm.py", line 1, in <module>
    from airllm import AutoModel
ImportError: cannot import name 'AutoModel' from partially initialized module 'airllm' (most likely due to a circular import) (/Users/samarthpusalkar/Desktop/airllm.py)
```

I tried installing uninstalling transformers library using the default with airllm install, but still got the same error.

Any help would be appreciated :)

**Comment by samarthpusalkar** [comment]
Sorry guys, just realised my file name was airllm.py and it was unable to resolve the correct module
