### ISSUE TITLE
layer_name 在使用前没有被定义

### ISSUE THREAD

**Issue by yjleo17** [lyogavin/airllm#162]
当我在使用garage-bAInd/Platypus2-70B-instruct模型的时候，所有模型下载完成后，在推理过程中出现了Traceback (most recent call last):
  File "d:\workspace\llama\main.py", line 42, in <module>
    generation_output = model.generate(
  File "d:\workspace\llama\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "d:\workspace\llama\venv\lib\site-packages\transformers\generation\utils.py", line 1914, in generate
    result = self._sample(
  File "d:\workspace\llama\venv\lib\site-packages\transformers\generation\utils.py", line 2651, in _sample
    outputs = self(
  File "d:\workspace\llama\venv\lib\site-packages\airllm\airllm_base.py", line 364, in __call__
    return self.forward(*args, **kwargs)
  File "d:\workspace\llama\venv\lib\site-packages\airllm\airllm_base.py", line 464, in forward
    moved_layers = self.move_layer_to_device(state_dict)
  File "d:\workspace\llama\venv\lib\site-packages\airllm\airllm_base.py", line 301, in move_layer_to_device
    layers.append(layer_name)
UnboundLocalError: local variable 'layer_name' referenced before assignment
我尝试了很多方法没有解决

**Comment by lyogavin** [comment]
fixed in airllm==2.9.1, please try it.

**Comment by ElectricMs** [comment]
更新到airllm2.9.1，使用Qwen/Qwen-7B的演示代码也出现了相似的错误
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In[11], line 23
     10 input_text = [
     11         #'What is the capital of China?',
     12         'I like',
     13     ]
     15 input_tokens = model.tokenizer(input_text,
     16     return_tensors="pt",
     17     return_attention_mask=False,
   (...)
     20     #padding=True
     21     )
---> 23 generation_output = model.generate(
     24     input_tokens['input_ids'].cuda(),
     25     max_new_tokens=3,
     26     use_cache=True,
     27     return_dict_in_generate=True)
     29 model.tokenizer.decode(generation_output.sequences[0])

File D:\software\anaconda3\envs\python39\lib\site-packages\torch\utils\_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File D:\software\anaconda3\envs\python39\lib\site-packages\transformers\generation\utils.py:1914, in GenerationMixin.generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, assistant_model, streamer, negative_prompt_ids, negative_prompt_attention_mask, **kwargs)
   1906     input_ids, model_kwargs = self._expand_inputs_for_generation(
   1907         input_ids=input_ids,
   1908         expand_size=generation_config.num_return_sequences,
   1909         is_encoder_decoder=self.config.is_encoder_decoder,
   1910         **model_kwargs,
   1911     )
   1913     # 13. run sample (it degenerates to greedy search when `generation_config.do_sample=False`)
-> 1914     result = self._sample(
   1915         input_ids,
   1916         logits_processor=prepared_logits_processor,
   1917         logits_warper=prepared_logits_warper,
   1918         stopping_criteria=prepared_stopping_criteria,
   1919         generation_config=generation_config,
   1920         synced_gpus=synced_gpus,
   1921         streamer=streamer,
   1922         **model_kwargs,
   1923     )
   1925 elif generation_mode in (GenerationMode.BEAM_SAMPLE, GenerationMode.BEAM_SEARCH):
   1926     # 11. prepare logits warper
   1927     prepared_logits_warper = (
   1928         self._get_logits_warper(generation_config, device=input_ids.device)
   1929         if generation_config.do_sample
   1930         else None
   1931     )

File D:\software\anaconda3\envs\python39\lib\site-packages\transformers\generation\utils.py:2651, in GenerationMixin._sample(self, input_ids, logits_processor, stopping_criteria, generation_config, synced_gpus, streamer, logits_warper, **model_kwargs)
   2648 model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
   2650 # forward pass to get next token
-> 2651 outputs = self(
   2652     **model_inputs,
   2653     return_dict=True,
   2654     output_attentions=output_attentions,
   2655     output_hidden_states=output_hidden_states,
   2656 )
   2658 if synced_gpus and this_peer_finished:
   2659     continue  # don't waste resources running the code we don't need

File D:\software\anaconda3\envs\python39\lib\site-packages\airllm\airllm_base.py:364, in AirLLMBaseModel.__call__(self, *args, **kwargs)
    363 def __call__(self, *args, **kwargs):
--> 364     return self.forward(*args, **kwargs)

File D:\software\anaconda3\envs\python39\lib\site-packages\airllm\airllm_base.py:464, in AirLLMBaseModel.forward(self, input_ids, attention_mask, position_ids, past_key_values, inputs_embeds, labels, use_cache, output_attentions, output_hidden_states, return_dict)
    462 if self.profiling_mode:
    463     t = time.time()
--> 464 moved_layers = self.move_layer_to_device(state_dict)
    465 if self.profiling_mode:
    466     elapsed_time = time.time() - t

File D:\software\anaconda3\envs\python39\lib\site-packages\airllm\airllm_base.py:301, in AirLLMBaseModel.move_layer_to_device(self, state_dict)
    299 for param_name, param in state_dict.items():
    300     if self.hf_quantizer is None:
--> 301         layers.append(layer_name)
    302     else:
    303         if '.weight' in param_name:

UnboundLocalError: local variable 'layer_name' referenced before assignment

**Comment by lyogavin** [comment]
Weird. I just tried, the code is different from my side.

Can you try again and make sure you have 2.9.1?

`pip list | grep airllm`

**Comment by ElectricMs** [comment]
I have reinstalled airllm and rechecked the sample, now the problem has been resolved! Thanks!

**Comment by lyogavin** [comment]
This looks like it was caused by the pre-3.0 layer-splitting / custom-model path, which was rewritten in v3.0.x to build on the standard Transformers model (generic streaming for any *ForCausalLM, with fixed shard handling and dtype). It should be resolved on v3.0.1 for standard architectures. Closing — please `pip install -U airllm` (>=3.0.1) and reopen with details if it still happens.
