### ISSUE TITLE
name 'dynamically_import_QuantLinear' is not defined

### ISSUE THREAD

**Issue by gyyixr** [lyogavin/airllm#163]
env:
ubuntu22.04 LTS
python==3.10
transformers==4.43.3
airllm==2.9.1
model=https://modelscope.cn/models/LLM-Research/Meta-Llama-3.1-405B-Instruct-GPTQ-INT4
code is from run_llama3.1_405B.ipynb
error:
python3 llama3.1-405b-test.py 
>>>> cache_utils installed
found index file...
found_layers:{'model.embed_tokens.': True, 'model.layers.0.': True, 'model.layers.1.': True, 'model.layers.2.': True, 'model.layers.3.': True, 'model.layers.4.': True, 'model.layers.5.': True, 'model.layers.6.': True, 'model.layers.7.': True, 'model.layers.8.': True, 'model.layers.9.': True, 'model.layers.10.': True, 'model.layers.11.': True, 'model.layers.12.': True, 'model.layers.13.': True, 'model.layers.14.': True, 'model.layers.15.': True, 'model.layers.16.': True, 'model.layers.17.': True, 'model.layers.18.': True, 'model.layers.19.': True, 'model.layers.20.': True, 'model.layers.21.': True, 'model.layers.22.': True, 'model.layers.23.': True, 'model.layers.24.': True, 'model.layers.25.': True, 'model.layers.26.': True, 'model.layers.27.': True, 'model.layers.28.': True, 'model.layers.29.': True, 'model.layers.30.': True, 'model.layers.31.': True, 'model.layers.32.': True, 'model.layers.33.': True, 'model.layers.34.': True, 'model.layers.35.': True, 'model.layers.36.': True, 'model.layers.37.': True, 'model.layers.38.': True, 'model.layers.39.': True, 'model.layers.40.': True, 'model.layers.41.': True, 'model.layers.42.': True, 'model.layers.43.': True, 'model.layers.44.': True, 'model.layers.45.': True, 'model.layers.46.': True, 'model.layers.47.': True, 'model.layers.48.': True, 'model.layers.49.': True, 'model.layers.50.': True, 'model.layers.51.': True, 'model.layers.52.': True, 'model.layers.53.': True, 'model.layers.54.': True, 'model.layers.55.': True, 'model.layers.56.': True, 'model.layers.57.': True, 'model.layers.58.': True, 'model.layers.59.': True, 'model.layers.60.': True, 'model.layers.61.': True, 'model.layers.62.': True, 'model.layers.63.': True, 'model.layers.64.': True, 'model.layers.65.': True, 'model.layers.66.': True, 'model.layers.67.': True, 'model.layers.68.': True, 'model.layers.69.': True, 'model.layers.70.': True, 'model.layers.71.': True, 'model.layers.72.': True, 'model.layers.73.': True, 'model.layers.74.': True, 'model.layers.75.': True, 'model.layers.76.': True, 'model.layers.77.': True, 'model.layers.78.': True, 'model.layers.79.': True, 'model.layers.80.': True, 'model.layers.81.': True, 'model.layers.82.': True, 'model.layers.83.': True, 'model.layers.84.': True, 'model.layers.85.': True, 'model.layers.86.': True, 'model.layers.87.': True, 'model.layers.88.': True, 'model.layers.89.': True, 'model.layers.90.': True, 'model.layers.91.': True, 'model.layers.92.': True, 'model.layers.93.': True, 'model.layers.94.': True, 'model.layers.95.': True, 'model.layers.96.': True, 'model.layers.97.': True, 'model.layers.98.': True, 'model.layers.99.': True, 'model.layers.100.': True, 'model.layers.101.': True, 'model.layers.102.': True, 'model.layers.103.': True, 'model.layers.104.': True, 'model.layers.105.': True, 'model.layers.106.': True, 'model.layers.107.': True, 'model.layers.108.': True, 'model.layers.109.': True, 'model.layers.110.': True, 'model.layers.111.': True, 'model.layers.112.': True, 'model.layers.113.': True, 'model.layers.114.': True, 'model.layers.115.': True, 'model.layers.116.': True, 'model.layers.117.': True, 'model.layers.118.': True, 'model.layers.119.': True, 'model.layers.120.': True, 'model.layers.121.': True, 'model.layers.122.': True, 'model.layers.123.': True, 'model.layers.124.': True, 'model.layers.125.': True, 'model.norm.': True, 'lm_head.': True}
saved layers already found in /home/gyy/Documents/model-file/Meta-Llama-3.1-405B-Instruct-GPTQ-INT4/splitted_model
new version of transfomer, no need to use BetterTransformer, try setting attn impl to sdpa...
attn imp: <class 'transformers.models.llama.modeling_llama.LlamaSdpaAttention'>
Traceback (most recent call last):
  File "/home/gyy/Documents/pyhon/llama3.1-405b-test.py", line 5, in <module>
    model = AutoModel.from_pretrained("/home/gyy/Documents/model-file/Meta-Llama-3.1-405B-Instruct-GPTQ-INT4")
  File "/home/gyy/anaconda3/envs/airllm/lib/python3.10/site-packages/airllm/auto_model.py", line 54, in from_pretrained
    return class_(pretrained_model_name_or_path, *inputs, ** kwargs)
  File "/home/gyy/anaconda3/envs/airllm/lib/python3.10/site-packages/airllm/airllm.py", line 9, in __init__
    super(AirLLMLlama2, self).__init__(*args, **kwargs)
  File "/home/gyy/anaconda3/envs/airllm/lib/python3.10/site-packages/airllm/airllm_base.py", line 131, in __init__
    self.init_model()
  File "/home/gyy/anaconda3/envs/airllm/lib/python3.10/site-packages/airllm/airllm_base.py", line 223, in init_model
    self.hf_quantizer.preprocess_model(model = self.model, device_map = device_map)
  File "/home/gyy/anaconda3/envs/airllm/lib/python3.10/site-packages/transformers/quantizers/base.py", line 182, in preprocess_model
    return self._process_model_before_weight_loading(model, **kwargs)
  File "/home/gyy/anaconda3/envs/airllm/lib/python3.10/site-packages/transformers/quantizers/quantizer_gptq.py", line 76, in _process_model_before_weight_loading
    model = self.optimum_quantizer.convert_model(model)
  File "/home/gyy/anaconda3/envs/airllm/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 229, in convert_model
    self._replace_by_quant_layers(model, layers_to_be_replaced)
  File "/home/gyy/anaconda3/envs/airllm/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 256, in _replace_by_quant_layers
    QuantLinear = dynamically_import_QuantLinear(
NameError: name 'dynamically_import_QuantLinear' is not defined

**Comment by gyyixr** [comment]
optimum==1.21.2(latest)

**Comment by lyogavin** [comment]
will look into supporting gptq
