### ISSUE TITLE
mlx Linear weight arrays were loaded with a dict of arrays

### ISSUE THREAD

**Issue by shiwanlin** [lyogavin/airllm#168]
Trying to run llama 3.1 405B

1. Env
----------
A pristine Apple native Conda env on a Mac M1 Pro:

```
          conda version : 24.5.0
    conda-build version : 24.5.1
         **python version : 3.12.4.final.0**
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=24.5.0=0
                          __osx=14.5=0
                          __unix=0=0
               platform : osx-arm64
             user-agent : conda/24.5.0 requests/2.32.2 CPython/3.12.4 Darwin/23.5.0 OSX/14.5 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8 aau/0.4.4 c/. s/. e/.

mlx: 16.1
airllm version: 2.9.1 for py3
```

2. testing codes:
----------
```
from airllm import AutoModel
import mlx.core as mx

MAX_LENGTH = 128
# or use model's local path...
model = AutoModel.from_pretrained("/Users/xxx/.cache/huggingface/hub/models--unsloth--Meta-Llama-3.1-405B-Instruct-bnb-4bit/snapshots/3bc95c334b4cbea9e55e90b98bfa7a3025b4be6c")

input_text = [
		"what's the capital of the U.S.?"
    ]

input_tokens = model.tokenizer(input_text,
#    return_tensors="pt", 
    return_tensors="np", 
    return_attention_mask=False, 
    truncation=True, 
    max_length=MAX_LENGTH, 
    padding=False)
 
print("input_tokons=", input_tokens)
 
generation_output = model.generate(
#   input_tokens['input_ids'].cuda(), 
    mx.array(input_tokens['input_ids']), 
    max_new_tokens=3,
    use_cache=True,
    return_dict_in_generate=True)

#? output = model.tokenizer.decode(generation_output.sequences[0])
#? print(output)

print(generation_output)

```
3. Error
----------
```
Traceback (most recent call last):
  File "/Volumes/backup-2-SG/AI-Models/airllm/run.py", line 31, in <module>
    generation_output = model.generate(
                        ^^^^^^^^^^^^^^^
  File "/Users/xxx/opt/anaconda3/envs/native/lib/python3.12/site-packages/airllm/airllm_llama_mlx.py", line 257, in generate
    for token in self.model_generate(x, temperature=temperature):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/opt/anaconda3/envs/native/lib/python3.12/site-packages/airllm/airllm_llama_mlx.py", line 316, in model_generate
    x, c = l(x, mask=mask)
           ^^^^^^^^^^^^^^^
  File "/Users/xxx/opt/anaconda3/envs/native/lib/python3.12/site-packages/airllm/airllm_llama_mlx.py", line 176, in __call__
    r, cache = self.attention(self.attention_norm(x), mask, cache)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/opt/anaconda3/envs/native/lib/python3.12/site-packages/airllm/airllm_llama_mlx.py", line 116, in __call__
    queries, keys, values = self.wq(x), self.wk(x), self.wv(x)
                            ^^^^^^^^^^
  File "/Users/xxx/opt/anaconda3/envs/native/lib/python3.12/site-packages/mlx/nn/layers/linear.py", line 73, in __call__
    x = x @ self["weight"].T
            ^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'T'

```
What happens is that the mlx array in the mlx Linear class (/mlx/nn/layers/linear.py) is loaded with a dict of arrays:

`In the __int__():`
```
__init__ weight=array([[0.00658072, -0.00517109, -0.00364805, ..., -0.000809977, -0.00707354, -0.0019196],
       [-0.000980511, -0.00501848, -0.00506598, ..., 0.00243317, -8.24607e-05, -0.00507284],
       [0.00738335, -0.00477193, -0.007584, ..., -0.00563658, -0.0042617, -0.00562789],
       ...,
       [0.00523609, 0.00059267, 0.00303091, ..., -0.00574442, -2.54996e-05, 0.000399888],
       [-0.00462547, -0.000150905, -0.00363434, ..., -0.00702133, -0.00329231, -0.000827513],
       [0.00386262, -0.00235723, -0.00739348, ..., 0.00593159, 0.00049083, -0.00277299]], dtype=float32)

```
`in the __call__():`

```
__call__ self['weight']={'quant_map': array([-1, -0.696289, -0.524902, ..., 0.5625, 0.723145, 1], dtype=float16), 'nested_quant_map': array([-0.993164, -0.979004, -0.964844, ..., 0.979004, 0.993164, 1], dtype=float16), 'nested_absmax': array([0.0379944, 0.0409241, 0.0394592, ..., 0.0594788, 0.106873, 0.059967], dtype=float16), 'absmax': array([42, 41, 42, ..., 206, 182, 192], dtype=float16), '': array([[32],
       [183],
       [99],
       ...,
       [52],
       [103],
       [140]], dtype=float16), 'quant_state': {'bitsandbytes__nf4': array([123, 34, 113, ..., 48, 51, 125], dtype=float16)}}
```

I guess this may be another mis-setting somewhere? Has anyone tried to run this model in the Apple silicon successfully?

Any help is appreciated!

**Comment by shiwanlin** [comment]
My guess this has to do with bitsandbytes are not supported for mlx...

**Comment by d-r-w** [comment]
I read these things all separately and (guessing) came to the same conclusion:

>[2023/12/25] v2.8.2: Support MacOS running 70B large language models.

>Just install airllm and run the code the same as on linux. See more in [Quick Start](https://github.com/lyogavin/airllm/tree/main?tab=readme-ov-file#quickstart).

>make sure you installed [mlx](https://github.com/ml-explore/mlx?tab=readme-ov-file#installation) and torch

>[2024/07/30] Support Llama3.1 405B ([example notebook](https://colab.research.google.com/github/lyogavin/airllm/blob/main/air_llm/examples/run_llama3.1_405B.ipynb)). Support 8bit/4bit quantization.

When you read the documentation like this, it is presented in a way where it's saying "yes this is totally possible with mlx" whereas that's not necessarily the case.
